# Created by: Hajime Kurita
# Purpose: Set up your mac for development
# Usage:
# ansible-playbook -i hosts developer-environment.yml

- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  environment:
    BERKELEYDB_DIR: /usr/local/Cellar/berkeley-db/6.1.26
    YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION: yes

  roles:
    - homebrew
    - homebrew-cask
    - atom
  vars:
    homebrew_repositories:
      - aspnet/dnx

    # homebreew is an admin system of mac packages especially for developers / normal user can use
    homebrew_packages:
      - ansible
      - berkeley-db
      - dnvm
      - docker
      - git
      - git-flow
      - heroku-toolbelt
      - imagemagick
      - mongodb
      - mysql
      - nvm
      - node
# - { name: openssl, state: linked, install_options: force }
      - openssl
      - peco
      - perl
      - python3
      - rbenv
      - readline
      - ruby
      - ruby-build
      - tmux
      - the_silver_searcher
      - vim
      - wget
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting

    # homebrew_cask is an admin system of mac packages especially for developers / normal user can use
    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:

    homebrew_cask_packages:
      - atom
      - dash
      - firefox
      - flux
      - google-chrome
      - google-japanese-ime
      - iterm2
      - java
      - karabiner
      - phpstorm
      - rubymine
      - skype
      - slack
      - spark
      - sublime-text
      - vagrant
      - virtualbox
      - visual-studio-code

    atom_packages_packages:
      - color-picker
      - grunt-runner
      - highlight-column
      - highlight-line
# ato crush
#      - minimap
      - preview
      - project-manager
      - script

  tasks:
    - name: Install Python Libraries
      pip: name={{ item }} state=latest executable=pip3
      with_items:
        - awscli
        - beautifulsoup4
        - boto
        - bsddb3
# dont't install bson / customized bson will be installed with pymongo
#        - bson
        - datetime
        - docker-py
        - pymongo
        - urlparse3
        - virtualenv
      environment:
        PYTHONPATH: ""

    - name: Install Node.js Libraries
      npm: name={{ item }} state=latest global=yes
      with_items:
        - generator-aspnet
        - mup
        - yo

    - name: Set up mac
      shell: defaults write com.apple.desktopservices DSDontWriteNetworkStores true
